name: Aider on Issue Labeled

on:
  workflow_call:
    inputs:
      issue-number:
        description: 'The issue number to generate the PR from'
        required: true
        type: number
      base-branch:
        description: 'The base branch to open the PR against'
        required: true
        type: string
    secrets:
      anthropic_api_key:
        required: true

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Pull Request
      - uses: mirrajabi/aider-github-workflows/.github/workflows/aider-issue-to-pr.yml@main
        with:
          issue-number: ${{ inputs.issue-number }}
          base-branch: ${{ inputs.base-branch }}
        secrets:
          anthropic_api_key: ${{ secrets.anthropic_api_key }}
